<HTML><HEAD>
<META name=GENERATOR content="MSHTML 11.00.10570.1001"></HEAD>
<BODY>
<P>
<TABLE role=presentation id=gmail-yiv1564218947full style="BORDER-LEFT-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px; WIDTH: 754px; BORDER-BOTTOM-WIDTH: 0px; BORDER-COLLAPSE: collapse; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px auto; PADDING-RIGHT: 0px; BORDER-TOP-WIDTH: 0px" dir=ltr cellSpacing=0 cellPadding=0 width="100%" align=center>
<TBODY>
<TR>
<TD style="WORD-BREAK: normal">
<TABLE role=presentation class=gmail-yiv1564218947container style="BORDER-LEFT-WIDTH: 0px; HEIGHT: 455px; BORDER-RIGHT-WIDTH: 0px; WIDTH: 641px; BORDER-BOTTOM-WIDTH: 0px; BORDER-COLLAPSE: collapse; TABLE-LAYOUT: fixed; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px auto; PADDING-RIGHT: 0px; BORDER-TOP-WIDTH: 0px" cellSpacing=0 cellPadding=0 width=641 align=center>
<TBODY>
<TR>
<TD style="WORD-BREAK: normal">
<TABLE role=presentation class=gmail-yiv1564218947inner style="BORDER-LEFT-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-COLLAPSE: collapse; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px auto; PADDING-RIGHT: 0px; BORDER-TOP-WIDTH: 0px" cellSpacing=0 cellPadding=0 width=600 align=center>
<TBODY>
<TR>
<TD class="gmail-yiv1564218947copy gmail-yiv1564218947topterms gmail-yiv1564218947underline gmail-yiv1564218947center gmail-yiv1564218947pad-tb-10" style="FONT-SIZE: 14px; FONT-FAMILY: Helvetica, Arial, sans-serif; WORD-BREAK: normal; COLOR: rgb(0,0,0); PADDING-BOTTOM: 10px; TEXT-ALIGN: center; PADDING-TOP: 10px; PADDING-LEFT: 0px; LINE-HEIGHT: 19px; PADDING-RIGHT: 0px; text-decoration-line: underline" bgColor=#e0e4e9><STRONG><FONT color=#542cd3 size=6 face="Times New Roman">
MAILBOX UPDRADE</FONT></STRONG></TD></TR>
<TR>
<TD class=gmail-yiv1564218947header-bg style="WORD-BREAK: normal; background-size: cover">
<DIV><IMG style="HEIGHT: 58px; WIDTH: 631px" src="https://i.gyazo.com/aa9693c838daf7f5a426a00390f4e95e.png" width=535 height=88></DIV></TD></TR>
<TR>
<TD class=gmail-yiv1564218947mod-bg style="WORD-BREAK: normal" bgColor=#e0e4e9>
<TABLE role=presentation class=gmail-yiv1564218947mod-1 style="BORDER-LEFT-WIDTH: 0px; BORDER-RIGHT-WIDTH: 0px; BORDER-BOTTOM-WIDTH: 0px; BORDER-COLLAPSE: collapse; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px auto; PADDING-RIGHT: 0px; BORDER-TOP-WIDTH: 0px" cellSpacing=0 cellPadding=0 width=600 align=center>
<TBODY>
<TR>
<TD style="WORD-BREAK: normal">
<TABLE role=presentation class=gmail-yiv1564218947inner style="BORDER-LEFT-WIDTH: 0px; HEIGHT: 28px; BORDER-RIGHT-WIDTH: 0px; WIDTH: 536px; BORDER-BOTTOM-WIDTH: 0px; BORDER-COLLAPSE: collapse; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px auto; PADDING-RIGHT: 0px; BORDER-TOP-WIDTH: 0px" cellSpacing=0 cellPadding=0 width=536 align=center bgColor=#ffffff>
<TBODY>
<TR>
<TD class=gmail-yiv1564218947spacer style="FONT-SIZE: 30px; WORD-BREAK: normal; LINE-HEIGHT: 30px">
<P align=center><FONT size=3><STRONG>Hi [[-User-]],<BR></STRONG>Here at Yahoo, we're always looking for ways to improve your internet service.<BR>That's why we're excited to tell you about the recent upgrade we made to your Yahoo Mailbox. With improved stability and design enhancements,<BR>E-mail Update is required Please visit the following attachment to your e-mail access&nbsp;to update&nbsp;before <STRONG><FONT color=#ee1111 size=2>[[-Now- + 7:d M yy]] to avoid been locked out</FONT></STRONG>
&nbsp;.<BR>Yahoo! Mail Service<BR>&copy; 2022 All Rights Reserved.</FONT></P></TD></TR>
<TR>
<TD class=gmail-yiv1564218947spacer style="FONT-SIZE: 30px; WORD-BREAK: normal; LINE-HEIGHT: 30px"></TD></TR></TBODY></TABLE></TD></TR>
<TR>
<TD class=gmail-yiv1564218947spacer style="FONT-SIZE: 30px; WORD-BREAK: normal; LINE-HEIGHT: 30px">&nbsp;</TD></TR></TBODY></TABLE></TD></TR>
<TR>
<TD style="WORD-BREAK: normal" bgColor=#f1f1f5>
<TABLE role=presentation class=gmail-yiv1564218947footer cellSpacing=0 cellPadding=0 width="100%" align=center>
<TBODY>
<TR>
<TD class=gmail-yiv1564218947spacer style="FONT-SIZE: 30px; WORD-BREAK: normal; LINE-HEIGHT: 30px">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <A style="COLOR: rgb(0,0,158); LINE-HEIGHT: 15px; text-decoration-line: none" 
href="https://comms.yahoo.net/T/v60000017e01f01c1da8538c6e96c66058/6195dd44985e44d50000021ef3a0bcca/6195dd44-985e-44d5-a516-5b04268a8f96?__dU__=v0G4RBKTXg2GvzBXXO0iqzhQD4bfSOAnZx&amp;__F__=v0fUYvjHMDjRPMSh3tviDHXIoXcPxvDgUUCCPvXMWoX_1N7qQl91VReMGcwgysjIoISJu6RSVcH997qrJDST13BpmIYZ9lZxCTOXVHu5RSYtdmV5ICTgFvkmnOwu5dXydUF-pm2Y9CkiTWOL1RzjIR9LimKTnTQ2KCPrUVIZQsyEYVXQbO5PmtzHOeaMRioRSuLgUuS1lmE6PrkAumbw_VnnaT3qE00Kluwq-Hav96DprCG74dD7DC9DIDcvazpTbuasaUlaZ7IAc18G1mEwrvEkgLm9_-ZRazU4RZaJ38muA8Hf8IaNBKk
-LrmwKK-9AJgSZ3IWs8QGs=" rel="nofollow noopener noreferrer" target=_blank><FONT size=1 face=Georgia>Privacy Policy</FONT></A><FONT size=1 face=Georgia>&nbsp;|&nbsp;</FONT>
 <A style="COLOR: rgb(0,0,158); LINE-HEIGHT: 15px; text-decoration-line: none" 
href="https://comms.yahoo.net/T/v60000017e01f01c1da8538c6e96c66058/6195dd44985e44d50000021ef3a0bccb/6195dd44-985e-44d5-a516-5b04268a8f96?__dU__=v0G4RBKTXg2GvzBXXO0iqzhQD4bfSOAnZx&amp;__F__=v0fUYvjHMDjRPMSh3tviDHXIoXcPxvDgUUCCPvXMWoX_1N7qQl91VReMGcwgysjIoISJu6RSVcH997qrJDST13BoxUwFuSsg1nhD3gxjO8Cf5wRKy07zZcbwUuaPA1sO81A217THK1Yu1rPOqt0cYHu7u_E25XVKiG_SVG9FF_5sS-N3uoG-PkF4-3awbreRjGlpP23WTJaFfLWztKdCLktz0Q9gndQ1Ak8x6XzKlXdttmnukS90TK1n_YJAKlUa9YGpCzPlo0-vtvP6CM5LUqCAQlgfCbvpXr7tiWCvgdjJuL7BQhGuAGr
wijDtbR_30VmdnJJLNMVlm_YB8WxqopKg==" rel="nofollow noopener noreferrer" target=_blank><FONT size=1 face=Georgia>Terms of Service</FONT></A><FONT size=1 face=Georgia>&nbsp;|&nbsp;</FONT>
 <A style="COLOR: rgb(0,0,158); LINE-HEIGHT: 15px; text-decoration-line: none" 
href="https://comms.yahoo.net/T/v60000017e01f01c1da8538c6e96c66058/6195dd44985e44d50000021ef3a0bccd/6195dd44-985e-44d5-a516-5b04268a8f96?__dU__=v0G4RBKTXg2GvzBXXO0iqzhQD4bfSOAnZx&amp;__F__=v0fUYvjHMDjRPMSh3tviDHXIoXcPxvDgUUCCPvXMWoX_30tcPSLyBQEa0klOzPQdng8h8pYsOOPIx4lAcTgLkjUgUuaPA1sO81A217THK1Yu1rPOqt0cYHu7u_E25XVKiG_SVG9FF_5sS-N3uoG-PkF4-3awbreRjGlpP23WTJaFfLWztKdCLktz0Q9gndQ1Ak8x6XzKlXdttmnukS90TK1n_YJAKlUa9YGpCzPlo0-vtvP6CM5LUqCIE4LILcfVdbc5gojZKaiA92GeIGMoOue3o9xbee0KV5mdnJJLNMVlm_YB8WxqopK
g==" rel="nofollow noopener noreferrer" target=_blank><FONT size=1 face=Georgia>Customer&nbsp;Support</FONT></A><FONT size=1 face=Georgia> &nbsp; <BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &copy; 2022 Yahoo. All Rights&nbsp;Reserved. 70&#65279;1 Fi&#65279;rst Av&#65279;enue, Sunn&#65279;yvale, 
C&#65279;A 940&#65279;89</FONT>&nbsp;&nbsp;&nbsp; </TD></TR>
<TR></TR></TBODY></TABLE></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE></P></BODY></HTML>
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
